homepage:
  pattern:  /
  defaults: { _controller: EmicroCoreBundle:Default:index }

login:
  pattern:  /login
  defaults: { _controller: EmicroCoreBundle:Auth:login }

signup:
  pattern:  /signup
  defaults: { _controller: EmicroCoreBundle:Auth:register }

logout:
  pattern:  /logout
  defaults: { _controller: EmicroCoreBundle:Auth:logout }

app:
  pattern:  /app
  defaults: { _controller: EmicroCoreBundle:App:index }

demo:
  pattern:  /demo
  defaults: { _controller: EmicroCoreBundle:Demo:index }

project_create:
  pattern:  /projects
  defaults: { _controller: EmicroCoreBundle:Project:create }
  requirements:
    _method: POST

canvas_create:
  pattern:  /canvases
  defaults: { _controller: EmicroCoreBundle:Canvas:create }
  requirements:
    _method: POST

canvas_embed:
  pattern:  /canvases/{id}
  defaults: { _controller: EmicroCoreBundle:Canvas:embed }
