parameters:
#    emicro_core.example.class: Emicro\Bundles\CoreBundle\Example

services:
#    emicro_core.example:
#        class: %emicro_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
